import shutil
import glob

def asHours(seconds: float) -> str:
    """
    Returns seconds to human-readable formatted string
    Args:
        seconds (float): total seconds
    Returns:
        str: total seconds converted to human-readable formatted string
    """
    m, s = divmod(seconds, 60)
    h, m = divmod(m, 60)
    return f"{h:.0f}h:{m:.0f}m:{s:.0f}s"

def delete_checkpoints(run_dir: str):
    """
    Deletes unecessary checkpoints generated by HuggingFace `Trainer`
    Args:
        run_dir (str): output directory where artifacts are saved
    """

    for file in glob.glob(f"{run_dir}/checkpoint-*"):
        shutil.rmtree(file, ignore_errors=True)